alert("please don't make noise!");
console.log("Hi I am Aashra Dangol.");
console.log("I am 18years old");
console.log(document.getElementById("paragraph").innerHTML);
console.log(typeof document);
document.getElementById("paragraph").innerHTML="<h1>HELLO</h1>";
// document.getElementById("paragraph").style.color="beige";
// document.getElementById("paragraph").style.backgroundColor="rgb(141, 189, 230)";
document.getElementById("paragraph").style.cssText="color:beige; background:rgb(141, 189, 230)";
const age = 10;
var age2 = 10;
age2=13;
let age3 = 10;
age3=23;
// var name;
var name="Aashra";
console.log(typeof age);
console.log(typeof age2);
console.log(typeof age3);
console.log( name);
console.log(prompt("Enter a name:"));
document.getElementById("message").innerHTML="Hello"+" "+"my name is:"+" "+ name + " "+"I am"+age+"years old.";